# Basic
title: Finger universe
subtitle: 用技术改变世界，改变普通人的生活
description: 若今生迷局深陷，射影含沙。便许你来世袖手天下，一幕繁华。你可愿转身落座，掌间朱砂，共我温酒煮茶
creator: <a href="http://onev.cat">@onevcat</a>
tabName: _用技术之手，扭转时局乾坤。

url: "https://1210958801.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Life, description: My Life, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 6899837886/profile?topnav=1&wvr=6
    github: 1210958801
    mail: lzyBeyond86@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

# 评论
netease_comment: false

gitalk:
   enable: true
   owner: 1210958801
   repo: 1210958801.github.io
   clientID: c10a240ff9c342206b7e
   clientSecret: 368e04a16d83c20ba308b2c5eabee5d87f061390
   admin: 1210958801